package com.example.padelVAR;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.widget.Button;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;

public class LiveAnalysisActivity extends AppCompatActivity {

    // Declare all buttons
    private Button btnBack;
    private Button btnShare;
    private Button btnVarDecision;
    private Button btnOpenWeb;
    private Button btnEmailReport;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_live_analysis);

        // Connect Java variables to XML views
        btnBack        = findViewById(R.id.btnBack);
        btnShare       = findViewById(R.id.btnShare);
        btnVarDecision = findViewById(R.id.btnVarDecision);
        btnOpenWeb     = findViewById(R.id.btnOpenWeb);
        btnEmailReport = findViewById(R.id.btnEmailReport);

        // ════════════════════════════════════════════
        // INTENT 1 — Go back to MainActivity
        // finish() closes this screen and returns to
        // the previous one in the back stack
        // ════════════════════════════════════════════
        btnBack.setOnClickListener(view -> {
            finish(); // Closes LiveAnalysisActivity, returns to MainActivity
        });

        // ════════════════════════════════════════════
        // INTENT 2 — Share text via any installed app
        // ACTION_SEND lets you share to WhatsApp,
        // Gmail, Messenger, etc — user picks which one
        // ════════════════════════════════════════════
        btnShare.setOnClickListener(view -> {
            Intent shareIntent = new Intent(Intent.ACTION_SEND);
            shareIntent.setType("text/plain");
            shareIntent.putExtra(Intent.EXTRA_SUBJECT, "Padel VAR Analysis");
            shareIntent.putExtra(Intent.EXTRA_TEXT,
                    "🎾 Check out this Padel VAR match analysis!\n" +
                            "Ball Speed: 247 km/h | Last Shot: IN | VAR Calls: 14\n" +
                            "Powered by AI Padel VAR System");
            // createChooser shows a popup letting user pick the app
            startActivity(Intent.createChooser(shareIntent, "Share Match Report via"));
        });

        // ════════════════════════════════════════════
        // INTENT 3 — Open browser to Padel rules page
        // ACTION_VIEW with a Uri opens any URL
        // in the phone's default browser
        // ════════════════════════════════════════════
        btnOpenWeb.setOnClickListener(view -> {
            Uri webUrl = Uri.parse("https://www.worldpadeltour.com");
            Intent browserIntent = new Intent(Intent.ACTION_VIEW, webUrl);
            startActivity(browserIntent);
        });

        // ════════════════════════════════════════════
        // INTENT 4 — Open email app with pre-filled fields
        // ACTION_SEND with type message/rfc822 opens
        // Gmail, Outlook, etc with subject and body ready
        // ════════════════════════════════════════════
        btnEmailReport.setOnClickListener(view -> {
            Intent emailIntent = new Intent(Intent.ACTION_SEND);
            emailIntent.setType("message/rfc822"); // This tells Android: open email apps only
            emailIntent.putExtra(Intent.EXTRA_EMAIL,
                    new String[]{"referee@padelvar.com"});  // To field
            emailIntent.putExtra(Intent.EXTRA_SUBJECT,
                    "Match Report — Padel VAR Analysis");   // Subject field
            emailIntent.putExtra(Intent.EXTRA_TEXT,
                    "Match Report Summary:\n\n" +
                            "• Ball Speed: 247 km/h\n" +
                            "• Last Shot Result: IN\n" +
                            "• Total VAR Calls: 14\n" +
                            "• AI Confidence: 72%\n\n" +
                            "Generated by Padel VAR AI System");    // Body field
            startActivity(Intent.createChooser(emailIntent, "Send Report via"));
        });

        // ════════════════════════════════════════════
        // INTENT 5 — Go to ReplayActivity
        // Also passes data (putExtra) to the next screen
        // ════════════════════════════════════════════
        btnVarDecision.setOnClickListener(view -> {
            // Show a quick popup message first
            Toast.makeText(this, "⚖ VAR Decision Requested!", Toast.LENGTH_SHORT).show();

            // Navigate to ReplayActivity AND send data with it
            Intent intent = new Intent(this, ReplayActivity.class);
            intent.putExtra("source", "live_analysis");    // Tell ReplayActivity where we came from
            intent.putExtra("ball_speed", 247);            // Pass the ball speed number
            intent.putExtra("last_shot", "IN");            // Pass the shot result
            startActivity(intent);
        });
    }
}