package com.example.padelVAR;

import android.Manifest;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.RequiresPermission;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import com.google.android.material.bottomnavigation.BottomNavigationView;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class LiveAnalysisActivity extends AppCompatActivity
        implements BluetoothLightController.ConnectionCallback {

    // ── Existing buttons ──────────────────────────────────────────────
    private Button btnBack, btnShare, btnVarDecision, btnOpenWeb, btnEmailReport;

    // ── Bluetooth light control ───────────────────────────────────────
    private Button btnBluetoothConnect, btnLightsOn, btnLightsDim, btnLightsOff;
    private TextView tvBluetoothStatus;
    private BluetoothLightController lightController;

    // Permission request code for Android 12+
    private static final int BT_PERMISSION_REQUEST = 2001;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_live_analysis);

        // ════════════════════════════════════════════
        // A: Wire existing buttons
        // ════════════════════════════════════════════
        btnBack        = findViewById(R.id.btnBack);
        btnShare       = findViewById(R.id.btnShare);
        btnVarDecision = findViewById(R.id.btnVarDecision);
        btnOpenWeb     = findViewById(R.id.btnOpenWeb);
        btnEmailReport = findViewById(R.id.btnEmailReport);

        // ════════════════════════════════════════════
        // B: Wire Bluetooth UI views (NEW)
        // ════════════════════════════════════════════
        btnBluetoothConnect = findViewById(R.id.btnBluetoothConnect);
        btnLightsOn         = findViewById(R.id.btnLightsOn);
        btnLightsDim        = findViewById(R.id.btnLightsDim);
        btnLightsOff        = findViewById(R.id.btnLightsOff);
        tvBluetoothStatus   = findViewById(R.id.tvBluetoothStatus);

        // Create the BT controller — 'this' implements ConnectionCallback
        lightController = new BluetoothLightController(this);

        // ════════════════════════════════════════════
        // C: Existing button logic (unchanged)
        // ════════════════════════════════════════════
        btnBack.setOnClickListener(v -> finish());

        btnShare.setOnClickListener(v -> {
            Intent shareIntent = new Intent(Intent.ACTION_SEND);
            shareIntent.setType("text/plain");
            shareIntent.putExtra(Intent.EXTRA_SUBJECT, "Padel VAR Analysis");
            shareIntent.putExtra(Intent.EXTRA_TEXT,
                    "🎾 Padel VAR match analysis!\n" +
                            "Ball Speed: 247 km/h | Last Shot: IN | VAR Calls: 14\n" +
                            "Powered by AI Padel VAR System");
            startActivity(Intent.createChooser(shareIntent, "Share Match Report via"));
        });

        btnOpenWeb.setOnClickListener(v -> {
            startActivity(new Intent(Intent.ACTION_VIEW,
                    Uri.parse("https://www.worldpadeltour.com")));
        });

        btnEmailReport.setOnClickListener(v -> {
            Intent emailIntent = new Intent(Intent.ACTION_SEND);
            emailIntent.setType("message/rfc822");
            emailIntent.putExtra(Intent.EXTRA_EMAIL,   new String[]{"referee@padelvar.com"});
            emailIntent.putExtra(Intent.EXTRA_SUBJECT, "Match Report — Padel VAR Analysis");
            emailIntent.putExtra(Intent.EXTRA_TEXT,
                    "Match Report Summary:\n\n" +
                            "• Ball Speed: 247 km/h\n• Last Shot Result: IN\n" +
                            "• Total VAR Calls: 14\n• AI Confidence: 72%\n\n" +
                            "Generated by Padel VAR AI System");
            startActivity(Intent.createChooser(emailIntent, "Send Report via"));
        });

        btnVarDecision.setOnClickListener(v -> {
            Toast.makeText(this, "⚖ VAR Decision Requested!", Toast.LENGTH_SHORT).show();
            Intent intent = new Intent(this, ReplayActivity.class);
            intent.putExtra("source",     "live_analysis");
            intent.putExtra("ball_speed", 247);
            intent.putExtra("last_shot",  "IN");
            startActivity(intent);
        });

        // ════════════════════════════════════════════
        // D: Bluetooth button logic (NEW)
        // ════════════════════════════════════════════
        btnBluetoothConnect.setOnClickListener(v -> handleBluetoothConnect());

        btnLightsOn.setOnClickListener(v -> {
            lightController.lightsOn();
            Toast.makeText(this, "💡 Court lights ON", Toast.LENGTH_SHORT).show();
        });

        btnLightsDim.setOnClickListener(v -> {
            lightController.lightsDim();
            Toast.makeText(this, "🌙 Court lights DIM", Toast.LENGTH_SHORT).show();
        });

        btnLightsOff.setOnClickListener(v -> {
            lightController.lightsOff();
            Toast.makeText(this, "⬛ Court lights OFF", Toast.LENGTH_SHORT).show();
        });

        // ════════════════════════════════════════════
        // E: Bottom navigation (NEW)
        // ════════════════════════════════════════════
        setupBottomNavigation();
    }

    // ─────────────────────────────────────────────
    // handleBluetoothConnect()
    // Checks permissions, then shows paired-device picker
    // ─────────────────────────────────────────────
    private void handleBluetoothConnect() {

        // If already connected, disconnect
        if (lightController.isConnected()) {
            lightController.disconnect();
            return;
        }

        // Check if Bluetooth is available
        if (!lightController.isBluetoothAvailable()) {
            Toast.makeText(this, "Bluetooth not supported on this device",
                    Toast.LENGTH_SHORT).show();
            return;
        }

        // Check if Bluetooth is turned on
        if (!lightController.isBluetoothEnabled()) {
            Toast.makeText(this, "Please enable Bluetooth first",
                    Toast.LENGTH_SHORT).show();
            startActivity(new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE));
            return;
        }

        // Android 12+ requires BLUETOOTH_CONNECT permission at runtime
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            if (ActivityCompat.checkSelfPermission(this,
                    Manifest.permission.BLUETOOTH_CONNECT)
                    != PackageManager.PERMISSION_GRANTED) {
                ActivityCompat.requestPermissions(this,
                        new String[]{
                                Manifest.permission.BLUETOOTH_CONNECT,
                                Manifest.permission.BLUETOOTH_SCAN
                        },
                        BT_PERMISSION_REQUEST);
                return;
            }
        }

        showPairedDevicesDialog();
    }

    // ─────────────────────────────────────────────
    // showPairedDevicesDialog()
    // Lists already-paired BT devices and lets the
    // user pick the light controller module
    // ─────────────────────────────────────────────
    @RequiresPermission(Manifest.permission.BLUETOOTH_CONNECT)
    private void showPairedDevicesDialog() {
        Set<BluetoothDevice> paired = lightController.getPairedDevices(this);

        if (paired == null || paired.isEmpty()) {
            Toast.makeText(this,
                    "No paired Bluetooth devices found.\n" +
                            "Pair your light controller in Android Settings first.",
                    Toast.LENGTH_LONG).show();
            return;
        }

        // Build list of device names to show in the dialog
        List<BluetoothDevice> deviceList  = new ArrayList<>(paired);
        String[]              deviceNames = new String[deviceList.size()];
        for (int i = 0; i < deviceList.size(); i++) {
            String name = deviceList.get(i).getName();
            deviceNames[i] = (name != null ? name : "Unknown") +
                    "\n" + deviceList.get(i).getAddress();
        }

        new AlertDialog.Builder(this)
                .setTitle("Select Light Controller")
                .setItems(deviceNames, (dialog, which) -> {
                    tvBluetoothStatus.setText("● Connecting...");
                    tvBluetoothStatus.setTextColor(0xFFFFD700);
                    if (ActivityCompat.checkSelfPermission(this, Manifest.permission.BLUETOOTH_SCAN) != PackageManager.PERMISSION_GRANTED) {
                        // TODO: Consider calling
                        //    ActivityCompat#requestPermissions
                        // here to request the missing permissions, and then overriding
                        //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
                        //                                          int[] grantResults)
                        // to handle the case where the user grants the permission. See the documentation
                        // for ActivityCompat#requestPermissions for more details.
                        return;
                    }
                    lightController.connectToDevice(deviceList.get(which), this);
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    // ─────────────────────────────────────────────
    // BluetoothLightController.ConnectionCallback
    // ─────────────────────────────────────────────
    @Override
    public void onConnected(String deviceName) {
        tvBluetoothStatus.setText("● " + deviceName);
        tvBluetoothStatus.setTextColor(0xFF2ECC71); // green
        btnBluetoothConnect.setText("🔵  Disconnect");

        // Enable the three light buttons now that we're connected
        btnLightsOn.setEnabled(true);
        btnLightsDim.setEnabled(true);
        btnLightsOff.setEnabled(true);

        Toast.makeText(this, "Connected to " + deviceName, Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onDisconnected() {
        tvBluetoothStatus.setText("● Disconnected");
        tvBluetoothStatus.setTextColor(0xFF888888);
        btnBluetoothConnect.setText("🔵  Connect to Light Controller");

        btnLightsOn.setEnabled(false);
        btnLightsDim.setEnabled(false);
        btnLightsOff.setEnabled(false);

        Toast.makeText(this, "Disconnected from Bluetooth device",
                Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onError(String message) {
        tvBluetoothStatus.setText("● Error");
        tvBluetoothStatus.setTextColor(0xFFFF4444); // red
        Toast.makeText(this, "BT Error: " + message, Toast.LENGTH_LONG).show();
    }

    // ─────────────────────────────────────────────
    // Permission result callback (Android 12+)
    // ─────────────────────────────────────────────
    @RequiresPermission(Manifest.permission.BLUETOOTH_CONNECT)
    @Override
    public void onRequestPermissionsResult(int requestCode,
                                           String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == BT_PERMISSION_REQUEST) {
            if (grantResults.length > 0 &&
                    grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                showPairedDevicesDialog();
            } else {
                Toast.makeText(this,
                        "Bluetooth permission denied", Toast.LENGTH_SHORT).show();
            }
        }
    }

    // ─────────────────────────────────────────────
    // Bottom Navigation
    // ─────────────────────────────────────────────
    private void setupBottomNavigation() {
        BottomNavigationView bottomNav = findViewById(R.id.bottomNavigationView);
        bottomNav.setSelectedItemId(R.id.nav_live);

        bottomNav.setOnItemSelectedListener(item -> {
            int id = item.getItemId();
            if (id == R.id.nav_live)   { return true; }
            if (id == R.id.nav_home)   { finish(); return true; }
            if (id == R.id.nav_replay) {
                startActivity(new Intent(this, ReplayActivity.class));
                overridePendingTransition(0, 0);
                return true;
            }
            if (id == R.id.nav_courts) {
                startActivity(new Intent(this, NearbyPadelCourtsActivity.class));
                overridePendingTransition(0, 0);
                return true;
            }
            return false;
        });
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (lightController != null && lightController.isConnected()) {
            lightController.disconnect();
        }
    }
}